spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=as6867909@gmail.com
spring.mail.password=9999999999
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
